# Generated by Django 5.0.3 on 2024-03-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=36,
                null=True,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
    ]
