# Generated by Django 5.0.3 on 2024-03-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=110, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="coursepayment",
            name="payment_link",
            field=models.URLField(
                blank=True, max_length=410, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
