# Generated by Django 5.0.3 on 2024-03-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(max_length=110, verbose_name="название"),
        ),
    ]
